### ISSUE TITLE
https://admin.thegreenwebfoundation.org/green-urls is 404

### ISSUE THREAD

**Issue by BR0kEN-** [thegreenwebfoundation/admin-portal#145]

**Comment by BR0kEN-** [comment]
@mrchrisadams please have a look.

**Comment by mrchrisadams** [comment]
Ah, oops ! sorry @BR0kEN.

I had been updating some of the admin, and forgot that the green url would move.

I'll be pushing a change to make the downloads accessible at the old url tomorrow, as I'm working to decouple this from django admin, but in the mean time, you can download the files at the link below instead.

https://admin.thegreenwebfoundation.org/admin/green-urls

**Comment by BR0kEN-** [comment]
Got it! Thanks for providing a new URL.

https://www.thegreenwebfoundation.org/green-web-datasets/ this page still links the old one.
