### ISSUE TITLE
Wordpress and django

### ISSUE THREAD

**Issue by jonathan-s** [thegreenwebfoundation/admin-portal#176]
@mrchrisadams I saw this repo > https://github.com/thegreenwebfoundation/wp-green-checker

And the readme was stated with uncertainty. So out of curiosity would it be for the current wordpress site or would be for something else, ie a plugin that someone can install on their site. 

If the former, perhaps it would be worth considering being consistent in platform choice and think about porting the wordpress stuff to django-wagtail.

**Comment by mrchrisadams** [comment]
Nah, it's for the wordpress site. We're doing a bit of work to give the main website a little makeover.

Not a big enough one to really cover the cost of making a whole new wagtail marketing/content site/

Wordpress is still  our content / marketing site, and Django is the underlying basis for the API and the member portal.

**Comment by jonathan-s** [comment]
Might be worth taking a look at whether this is possible / easy to implement > https://wordpress.org/plugins/simply-static/#description as part of that effort.

Not hitting the database or render any views should speed things up and take fewer resources.

**Comment by mrchrisadams** [comment]
Thanks for the suggestion Jonathan - I'm not too worried about us optimising the performance of the wordpress site right now.

It doesn't get enough traffic right now for this to really be necessary, and we're working with a couple of wordpress specialists for the refreshed version.

If traffic ramps up it might make sense, but I'm happy referring to them at the mo, as this is their domain of expertise. 

There's plenty to focus on for the django site in the meantime 👍
