### ISSUE TITLE
Add Google's IP public ranges, keyed by region into the checker

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#208]
Google describe they how list their public IP ranges for their various regions here

https://support.google.com/a/answer/10026322?hl=en

And you can see the json payload here, for the honking great IP ranges, keyed by region

https://www.gstatic.com/ipranges/cloud.json

Each region has a corresponding key in the JSON

So presumably, if you know the IP range, then you can map it to the corresponding region

https://github.com/GoogleCloudPlatform/region-carbon-info/blob/main/data/yearly/2020.csv

So `asia-south1`, otherwise known as Mumbai, might have an annualised grid carbon footprint of 721g

|Google Cloud Region|Location|Google CFE|Grid carbon intensity (gCO2eq / kWh)|Google Cloud net carbon emissions|
|-|-|-|-|-|
|asia-south1|Mumbai|0.12|721|0|
|asia-south2|Delhi|657|0|

https://github.com/GoogleCloudPlatform/region-carbon-info/blob/main/data/yearly/2020.csv#L7

And I _think_ you would be able to identify the region based on the IP ranges shared in the cloud.json file linked above.

```json
[
{
    "ipv4Prefix": "34.93.0.0/16",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "34.100.128.0/17",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "34.104.108.0/23",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "34.124.44.0/23",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.200.128.0/17",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.201.41.0/24",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.207.192.0/18",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.220.42.0/24",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.234.208.0/20",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.242.42.0/24",
    "service": "Google Cloud",
    "scope": "asia-south1"
  }, {
    "ipv4Prefix": "35.244.0.0/18",
    "service": "Google Cloud",
    "scope": "asia-south1"
  },
]
```

This assumes you're working with ipv4, not ipv6. I'm not sure how you'd tell afterwards.

TODO - we know we can do (not entirely reliable GeoIP lookups). Can you use this approach for region look-ups with most cloud providers? We ask for the city, so that might be enough in most cases.

**Comment by mrchrisadams** [comment]
Linking to the original AWS pull request
https://github.com/thegreenwebfoundation/admin-portal/pull/64

**Comment by roald-teunissen** [comment]
Maybe (this library)[https://ipinfo.io/] might help finding information like the location based on the IPv4.

**Comment by mrchrisadams** [comment]
Hi @roald-teunissen 

The ipinfo library is useful, but I think there's a cost per API call, and given we do more than 5 million requests a day on most days, I think the cost of doing this would be greater than the cost of running the entire infrastructur stack so far 😱

There is support for free, local geolocation inside the django framework, that should give data at a city level, and do so with local IP lookups, which would also be faster.

https://docs.djangoproject.com/en/4.0/ref/contrib/gis/geoip2/#django.contrib.gis.geoip2.GeoIP2

For the purposes of importing the google IP info, I don't think it's necessary, but it is a feature that I think is valuable.

I've created issue #245, which is tied to some earlier research work we were doing.

https://github.com/thegreenwebfoundation/admin-portal/issues/245

**Comment by roald-teunissen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [List Google's IP ranges](https://trello.com/c/zSc7NLjC/70-list-googles-ip-ranges)
