### ISSUE TITLE
[ENHANCEMENT] Importing Microsoft's dataset from an endpoint

### ISSUE THREAD

**Issue by roald-teunissen** [thegreenwebfoundation/admin-portal#253]
**Is your feature request related to a problem? Please describe.**
As of making this issue, we use a locally stored JSON file we once manually downloaded from the website.

**Describe the solution you'd like**
It would be nice to actually use an endpoint so it gets updated from time to time.
We downloaded the JSON [from this website.](https://www.microsoft.com/en-us/download/details.aspx?id=56519)
If you click on the button, it will redirect you to a page and by inspecting the webpage you can see that, as of making this issue, it downloaded from the following url: 
https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220516.json

A date can be extracted at the end of the file name (2022 05 16). Even though it is not the 16th of the month but actually the 23th, it indicated that this referral is not updated on a daily basis. We either need to figure out this url to get an endpoint or get in contact with Microsoft to retrieve a reliable endpoint.

**Describe alternatives you've considered**
A. Inspect the url overtime and guess the patterns 
B. Ask Microsoft for an endpoint

**Additional context**
We have already talked about this issue but I can't find it anymore. Presumably because the issue has been closed and the topic resolved.

**Comment by mrchrisadams** [comment]
Hey @roald-teunissen you can search for closed issues, by clicking the closed filter like so.

https://github.com/thegreenwebfoundation/admin-portal/issues?q=microsoft+is%3Aclosed

**Comment by roald-teunissen** [comment]
> Hey @roald-teunissen you can search for closed issues, by clicking the closed filter like so.
> 
> https://github.com/thegreenwebfoundation/admin-portal/issues?q=microsoft+is%3Aclosed
Thanks!
[Here is the PR I was looking for.](https://github.com/thegreenwebfoundation/admin-portal/pull/232)

**Comment by roald-teunissen** [comment]
The previous link is not working anymore. Therefore, this new one popped up: https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220606.json

As you can see, the only thing that changes is the name and therefore the date range of the json file.

**Comment by mrchrisadams** [comment]
Hmm… 

Ok, so let's check this - the only bit that changes is the filename:


```
https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220516.json
https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220606.json

```

Given that in our app we pull this from an environment variable anyway, if we have a way to check everyday if there is a new file, we might be able to just automate it by running a check on a cronjob, like the following:

```py

bucket = "https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63"

# this is probbably the wrong syntax but you get the idea
today_formatted = today.strftime("%Y%%D")

filename =  f"ServiceTags_Public_{today_formatted}.json"

ip_range_req = request.get(f"{bucket}/{filename}")

if  ip_range_req.ok:
    # imagine this as a function to update the environment variables  
    # for the machines in prod running the import
    update_environment_variable_in_deployed_environment_to(filename)

```

I've contact someone at M$ as well -- if they give us a nice consistent url, we might not need to write any code, but at elast we know we have the option now :D

**Comment by roald-teunissen** [comment]
Just a quick check in: 
The link has been updated to: https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220627.json
So it confirms again that only the date changes

**Comment by roald-teunissen** [comment]
Picking this ticket up from now with the following plan:
- Using object storage to track the latest endpoint (through boto3)
- Cronjob that occasionally refreshes this link
- Logic: testing multiple endpoint patterns to try and find a working one to refer to the latest version

**Comment by mrchrisadams** [comment]
Hi @roald-teunissen 

Once you have a bucket available with `green_domains_bucket`, you can `get` and `put` to it using the API outlined at the link below:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#bucket

Here's the link with code for taking something locally and uploading it to a given 'key' in the bucket:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.upload_file

Here's the link with code sample for fetching content:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.upload_file

**Note:** - the `green_domains_bucket` method currently fetches a bucket object specifically for working with the 
green domains. It might make sense to generalise the code in `object_storage.py` so you call an method like `object_storage_bucket(NAME)`, that is called  by `green_domains_bucket`.

Something like this:

```py

def object_storage_bucket(bucket_name: str) -> object_storage.Bucket:
   """
   Return a bucket to work with specified by bucket_name
   """
    session = boto3.Session(region_name=settings.OBJECT_STORAGE_REGION)
    object_storage = session.resource(
        "s3",
        endpoint_url=settings.OBJECT_STORAGE_ENDPOINT,
        aws_access_key_id=settings.OBJECT_STORAGE_ACCESS_KEY_ID,
        aws_secret_access_key=settings.OBJECT_STORAGE_SECRET_ACCESS_KEY,
    )
    return object_storage.Bucket(bucket_name)

def green_domains_bucket() -> object_storage.Bucket:
    """
    Return an object storage bucket containing snapshots
    of the green domain table
    """
    return object_storage_bucket(settings.DOMAIN_SNAPSHOT_BUCKET)


def daily_ip_imports_bucket() -> object_storage.Bucket:
    """
    Return an object storage bucket containing daily import for large providers
    """
    return object_storage_bucket(settings.DAILY_IP_NETWORK_IMPORT_BUCKET)

```

**Comment by mrchrisadams** [comment]
No longer needed since the refactor of our importers
