### ISSUE TITLE
[BUG] Company names not in alphabetic order

### ISSUE THREAD

**Issue by roald-teunissen** [thegreenwebfoundation/admin-portal#266]
**Describe the bug**
Hosting companies displayed on [the website](https://www.thegreenwebfoundation.org/directory/) and also retrieved from the API are not in alphabetic order.

**To Reproduce**
1. Retrieve hosting provider companies through the API as JSON or go to [the website](https://www.thegreenwebfoundation.org/directory/)

**Expected behavior**
Company names underneath each country is in alphabetic order.

**Actual behavior**
Company names are not in alphabetic order

**Visual proof**
![image](https://user-images.githubusercontent.com/8720223/177537074-95a41c92-668c-402b-b964-2782627b9e2d.png)

**Additional context**
[Check the Trello card that is connected to this issue.](https://trello.com/c/JZ6rTmcg/166-support-request-from-r-tuk-alphabetical-order)

**Comment by roald-teunissen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support request from: R Tuk (alphabetical order)](https://trello.com/c/JZ6rTmcg/166-support-request-from-r-tuk-alphabetical-order)

**Comment by tortila** [comment]
Just to confirm if I understood the issue: the expected behaviour is that the providers are sorted by: partner first, then alphabetically by name?
