### ISSUE TITLE
[FEATURE] Authenticated users are able to access their submissions

### ISSUE THREAD

**Issue by tortila** [thegreenwebfoundation/admin-portal#311]
**User story:**
Given a feature toggle is turned on for my particular account,
as an authenticated user
when I access the submissions page,
then I'm able to see all submissions related to my account.

**Acceptance criteria:**
- `/submissions` page (name to be confirmed) is accessible by selected users
- all submissions for the current user are shown on that page
- a feature flag enabling/disabling this access is managed by staff in the admin panel
- each submission has some data related to it (to be defined) and a status
- submissions panel is accessible by staff in the admin panel, sorted by `pending` submissions first 

**Developer notes:**
- This is the first task related to the new supplier portal. The focus is to model the data on the backend and make minimal changes on the front-end to expose this functionality to selected users (staff for now). 
- As pointed out by Chris, we can utilize [`django-waffle`](https://waffle.readthedocs.io/en/stable/index.html) to configure this new functionality behind a feature flag.
- We need to decide on which domain to expose this new functionality, for example: `portal.greenwebfoundation.org`, `app.greenwebfoundation.org`, etc.

**Comment by tortila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New registration form: Authenticated users are able to access their submissions](https://trello.com/c/skw5tzzP/3-new-registration-form-authenticated-users-are-able-to-access-their-submissions)

**Comment by mrchrisadams** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New registration form: Authenticated users are able to access their submissions](https://trello.com/c/skw5tzzP/3-new-registration-form-authenticated-users-are-able-to-access-their-submissions)

**Comment by tortila** [comment]
Today me and @mrchrisadams discussed the details of implementing this new feature. Here are some key decisions that we agreed on:
- We're going to continue implementing this feature in the existing Django app. Should we run into any limitations of this approach, we'll evaluate this decision again.
- There's a need for a new entity, like `ProviderRequest`, that will model the input to the system as we expect it. This current issue focuses on implementing it side by side to existing models in the back-end. In the following tasks we will tackle the translation layer: how does the `ProviderRequest` map to existing (and possibly new) objects, like `HostingProvider`, including validation. Choosing this approach allows us to decouple business logic from the presentation domain, and handle refactoring of the existing models independently of introducing a new feature on the provider request form.
- In the `ProviderRequest` model, we want to allow users to specify locations, each of them having a set of services offered by the provider in that location. We also want to allow users to include supporting evidence and possibly IP ranges per location.
- There's a foreseen need to introduce an audit trail `ProviderRequest`, which will allow us to track all the changes being made when the request is going back and forth between customer and support.
- `django-waffle` is already installed and enabled, but it's hidden in the admin panel on production by a custom code snippet. @mrchrisadams will remove that and enable waffle for staff members only.

**Comment by mrchrisadams** [comment]
Thanks for writing this up Oliwia. I'll make the separate issue for exposing django waffle to end users to Green web staff again

**Comment by mrchrisadams** [comment]
On the domain front:
My preference would be to serve this from `app.thegreenwebfoundation.org`, and gradually find way to phrase out `admin.thegreenwebfoundation.org` to represent the wider set of users who might use this info. 

I think it would make sense to keep the `api.thegreenwebfoundation.org` but eventually find a way to deploy and scale these separately, as they are likely to have very different usage patterns.

**Comment by mrchrisadams** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update listing of how providers list how they are associated with datacentres](https://trello.com/c/5vFOCJQ8/329-update-listing-of-how-providers-list-how-they-are-associated-with-datacentres)
