### ISSUE TITLE
[FEATURE] Provider-related resources are created automatically upon accepting their submission

### ISSUE THREAD

**Issue by tortila** [thegreenwebfoundation/admin-portal#313]
**User story:**
As a Green Web Foundation staff,
when I validate a submission from a provider and mark it as accepted in the admin panel,
then all resources related to that provider are automatically created in the system.

**Acceptance criteria:**
- there's a simple (ideally one-click) way to accept submissions in the admin panel, available to staff,
- accepting a submission triggers a fully automated process that creates `HostingProvider` and all related objects in the system, based on the data from the submission,
- submission status changes (`in review` -> `accepted` or similar) 
- all created objects are related to the user account that originally created the submission (i.e. the user is able to modify those objects in the admin panel).
- the link to the verification request is accessible to both staff and users who should have access (at present just the original author)

**Developer notes:**
- Open question: how to handle error cases? If for some reason the automated process fails, the staff should be able to see that. This could mean that the process should be synchronous: when the process completes, the staff should be presented with either: a descriptive error message or be redirected to the newly created `HostingProvider` object page.

**Handling failure modes**

Because we are creating providers from this, there are a few scenarios we need to account for. 

- [ ] **A user who is not already associated with a provider, is trying to create a provider with the same name**
- [ ] **ASN or IP ranges are already in use**
- [ ] **A user who is already associated with a provider, is trying to create a provider with the same name**

There are others, but it may make sense to address them separately. See trello for the suggested ways to recover in each case.

**Comment by hanopcan** [comment]
Hiya @mrchrisadams 

@tortila and I chatted through the scope of this ticket earlier in the week. In terms of effort and risk we rated this one as an 8+ (we used fibbonaci numbers for estimates, 1 2 3 5 8). 8+ suggests this work is too big for one ticket and needs breaking up into additional tickets. I don't think that will come as a surprise, @tortila made it clear how much there is to scope and decide in relation to this. It's a biggie.

The other thing I'd like to raise in the relation to this. @tortila explained to me there were a few new things we want to add in that the system can't cater for at the moment, specifically:
* mapping data centers to locations through cities;
* allowing providers to add in their supply chain.

I've flagged with you in other places I am a bit concerned about budget and timeline. I want to raise a question here: is all of this scope absolutely critical for the MVP to launch the new partners program? Can any of the scope be deferred until later? Can we find manual workaround for anything to help us speed up dev and get to launch quicker?  

The bit we talked through specifically was the supply chain part. Is this _really really_ needed? Is there any sense in launching some of the other new stuff first, learning from that and then coming back to this once the directory is delivered?

I left it with @tortila that you two are best placed to discuss this, and that if your conclusion is yes without all of this scope we are blocked to deliver on an MVP of the new directory then so be it. But I feel I have to be diligent and put the challenge to you both 😄
