### ISSUE TITLE
[DISCUSSION] Update AWS importer to refer to new regions and sustainability claims

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#321]
**Topic**

We've had a member of AWS staff, @sissonsb, open an issue on the older green check repo, asking about updating the info we have. I've created this issue for now, so we don't miss it.

**Reference**

This is a response to issue #75 on the older greencheck API repo:

https://github.com/thegreenwebfoundation/greencheck-api/issues/75

From the previous issue:

> Following the release of the Amazon annual sustainability report the Amazon public website was updated and now details an expanded list of AWS Regions that were powered by over 95% renewable energy in 2021.
> 
> "  
> To achieve our goal of powering our operations with 100% renewable energy by 2025—five years ahead of our original 2030 target—Amazon contracts for renewable power from utility scale wind and solar projects that add clean energy to the grid. These new renewable projects support hundreds of jobs while providing hundreds of millions of dollars of investment in local communities. We also may choose to support these grids through the purchase of environmental attributes, like Renewable Energy Certificates and Guarantees of Origin, in line with our [Renewable Energy Methodology](https://sustainability.aboutamazon.com/renewable-energy-methodology.pdf).
> 
> As a result, in 2021, the following AWS Regions were powered by over 95% renewable energy:
> 
> US East (Northern Virginia)  
> GovCloud (US-East)  
> US East (Ohio)  
> US West (Oregon)  
> GovCloud (US-West)  
> US West (Northern California)  
> Canada (Central)  
> Europe (Ireland)  
> Europe (Frankfurt)  
> Europe (London)

**Comment by mrchrisadams** [comment]
Sweet, I've heard back:

> The EC2 documentation has this mapping
>  
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions
>  
> You can also produce this programmatically using the CLI
>  
> aws ec2 describe-regions --all-regions
>  
> or SDKs eg boto3
> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_regions.html

I think the only ones not listed on the docs.aws.amazon.com page are for China.

Theyre's mention of them below, but I don't see the region names to import the IPs. 
https://www.amazonaws.cn/en/about-aws/china/

We might need to address that one separately.

**Comment by allanhenderson** [comment]
Hello, just wondered if any movement on this issue?  Thank you

**Comment by mrchrisadams** [comment]
hi @allanhenderson!

The new regions should have started showing up as green in our IP checks along with the information we have access to from Nov 11, 2023 - I should have updated this ticket here, sorry.

If you're seeing something different, the fastest way to receive a response about checks you see would be to send a message via support page listed below:

https://www.thegreenwebfoundation.org/support/

We have dedicated support team for looking into specific cases, but it's also worth knowing that we're in the process of deploying new versions of automated importers this week, for a select number of large cloud providers. As the page below says this includes AWS, Azure and Equinix.

More below:
https://www.thegreenwebfoundation.org/support/how-we-manage-ip-ranges-for-large-hosting-providers/

**Comment by mrchrisadams** [comment]
Once I've seen the updated cronjob that was set up via ansible working, I think we can close this ticket

**Comment by allanhenderson** [comment]
Hi @mrchrisadams , thank you very much indeed!
