### ISSUE TITLE
Users should be able to manage more than 1 hosting provider

### ISSUE THREAD

**Issue by tortila** [thegreenwebfoundation/admin-portal#335]
Currently there's a one-to-many relationship between hosting providers and users (via foreign key from User to Hostingprovider). This allows a single user to manage a single Hostingprovider, and multiple users can manage the same Hostingprovider. Now we want to enable users to manage multiple hosting provider objects.

Depending on whether we want to continue allowing multiple users to manage a single hosting provider, we should change this relationship to many-to-one or many-to-many

**Comment by tortila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to manage more than 1 hosting provider](https://trello.com/c/OeZn4Fhw/42-users-should-be-able-to-manage-more-than-1-hosting-provider)

**Comment by mrchrisadams** [comment]
I'm adding some links

This was the blog post about a well through through way to a grant access to objects give as a really good overview of the theory we might want to be aware of:
https://tailscale.com/blog/rbac-like-it-was-meant-to-be/

This talk here from djangocon is probably the best talk I can find to help understand common patterns for providing rich access control and object level permissions with django - it'd be really good to review before the planning session next week for this.
https://www.youtube.com/watch?v=svTt9F7MnDk

**Comment by tortila** [comment]
I started implementing object-level permissions using `django-guardian` and so far it looks like it covers all of our needs:
- build-in admin integration on the object change view (we can manage who has access to a hosting provider X on their admin page)
- users as well as groups are supported: https://django-guardian.readthedocs.io/en/stable/userguide/assign.html#for-group - this can be utilised in the future to implement a concept of organisations, covering multiple hosting provider objects, based on groups, and managing permissions on organisation level (FYI @mrchrisadams)
- our custom user admin needs to be extended to allow managing object-level permissions for a given user
