### ISSUE TITLE
Introduce "locations" that are assigned to hosting providers

### ISSUE THREAD

**Issue by tortila** [thegreenwebfoundation/admin-portal#336]
In the future we want to enable multiple locations per provider. 
Location should include: 
- country,
- city, 
- name, 
- possibly a geocoded point (to allow displaying on the map)

This task includes:
- modifying Hostingprovider model (remove country field), create a new Location model (that contains the country field) with a reference to the Hostingprovider
- migration of existing data

**Comment by tortila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Introduce "locations" that are assigned to hosting providers](https://trello.com/c/gFRRi3B1/43-introduce-locations-that-are-assigned-to-hosting-providers)

**Comment by mrchrisadams** [comment]
hey @tortila can I check what we'd need here?

We'd need to extend the `ProviderRegistrationView` with a something like a new entry in the FORMS list.

So here,

```py
FORMS = [
        (Steps.ORG_DETAILS.value, OrgDetailsForm),
        (Steps.SERVICES.value, ServicesForm),
        (Steps.GREEN_EVIDENCE.value, GreenEvidenceForm),
        (Steps.NETWORK_FOOTPRINT.value, NetworkFootprintForm),
        (Steps.CONSENT.value, ConsentForm),
    ]
```

We'd have something like this:

```py
FORMS = [
        (Steps.ORG_DETAILS.value, OrgDetailsForm),
        (Steps.LOCATIONS.value, OrgLocationForm),
        (Steps.SERVICES.value, ServicesForm),
        (Steps.GREEN_EVIDENCE.value, GreenEvidenceForm),
        (Steps.NETWORK_FOOTPRINT.value, NetworkFootprintForm),
        (Steps.CONSENT.value, ConsentForm),
    ]
```

And update the templates accordingly:

```py
TEMPLATES = {
        Steps.ORG_DETAILS.value: "provider_registration/about_org.html",
        Steps.LOCATIONS.value: "provider_registration/locations.html",
        Steps.SERVICES.value: "provider_registration/services.html",
        Steps.GREEN_EVIDENCE.value: "provider_registration/evidence.html",
        Steps.NETWORK_FOOTPRINT.value: "provider_registration/network_footprint.html",
        Steps.CONSENT.value: "provider_registration/consent.html",
    }
```

And then the `done ` method to deal with the form processing. This about right?

**Comment by tortila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create multiple locations as editable on a provider, and something we can use in the directory](https://trello.com/c/07SHWBuo/100-create-multiple-locations-as-editable-on-a-provider-and-something-we-can-use-in-the-directory)
