### ISSUE TITLE
Implement a new partnership model

### ISSUE THREAD

**Issue by tortila** [thegreenwebfoundation/admin-portal#340]
Currently we model a partnership status in `Hostingprovider` as a `CharField` with one of the following values:
```
    NONE = "None"
    PARTNER = "Partner"
    DEV_PARTNER = "Dev Partner"
    CERTIFIED_GOLD = "Certified Gold Partner"
    CERTIFIED_PARTNER = "Certified Partner"
    GOLD = "Gold Partner"
```
We agreed on a new model with 3 levels: provider, supporter and leader. This task is to figure out the mapping, implementing new partnership levels, and migrating existing data to it.

**Comment by mrchrisadams** [comment]
hey @tortila I just changed

> 3 levels: provider, supported and leader

to 

> 3 levels: provider, supporter and leader

Cool?
