### ISSUE TITLE
Update the registration form to reflect new designs

### ISSUE THREAD

**Issue by tortila** [thegreenwebfoundation/admin-portal#353]
The multi-step registration form was introduced in https://github.com/thegreenwebfoundation/admin-portal/issues/312 and:
- it was not styled at all,
- the wizard steps were based on old designs.

Now that [the new designs were delivered](https://www.figma.com/file/NvSI7x4mgfQkiWCJMzXixN/The-Green-Web-Foundation----Directory-redesign?node-id=58%3A56517), additional work is required to:
- update the form on each step to reflect the new designs,
- style the whole page.

**Comment by tortila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update the registration form to reflect new designs](https://trello.com/c/8YJHpwUb/62-update-the-registration-form-to-reflect-new-designs)

**Comment by hanopcan** [comment]
Hi @tortila Just to let you know I've done a whole bunch of work on this in this branch: #367 

I'd love for you to take a look when you get a moment and let me have any feedback. I'm sure there will still be some other bits to improve on it.

Was hoping to merge the branch in but the checks are failing and I'm not sure why. I've asked Chris to take a look at it.
