### ISSUE TITLE
[ENHANCEMENT] How to add html to form help text

### ISSUE THREAD

**Issue by hanopcan** [thegreenwebfoundation/admin-portal#374]
**Is your feature request related to a problem? Please describe.**
Justine has suggested that on the verification request form, in the services section we link out to a help article. It's a good idea and we may want to do this in a bunch of other places too, now and in the future. 

However, I'm not sure how we can add html into the help text. I know in WordPress for example sometimed HTML is sanitised deliberately from text strings. Maybe it is the case here too. I'm not sure.

**Describe the solution you'd like**
I'd like to know if it is possible to add HTML into the help text. And if it is possible, how might I do it please?

**Describe alternatives you've considered**
I've tried this:

```
    services = forms.MultipleChoiceField(
		choices=ProviderRequest.get_service_choices,
		widget=forms.CheckboxSelectMultiple,
		label="What hosting services do you offer?",
		help_text="Choose all the services that your organisation offers. <a href=&#34;https://www.thegreenwebfoundation.org/directory/services-offered/&#34;>More information on our services</a>"
	)
```

But it renders the link as `http://127.0.0.1:8000/requests/new/%22https://www.thegreenwebfoundation.org/directory/services-offered/%22`. I suspect this is the not the right way to embed HTML into this text string. 

**Additional context**
This is what I want it to do 

![Link in help text](https://user-images.githubusercontent.com/11687898/213207048-da6a14d7-9b2a-4d4b-80a5-d9c6763ae96e.jpg)

**Comment by mrchrisadams** [comment]
HI @hanopcan, I think you can use `mark_safe` in this scenario.

With the other imports at the of the file you'd add something like this

```py
from django.utils.safestring import mark_safe
```

That make the `mark_safe` function available.

Then later on you'd use it in the code like so:

```py
services = forms.MultipleChoiceField(
		choices=ProviderRequest.get_service_choices,
		widget=forms.CheckboxSelectMultiple,
		label="What hosting services do you offer?",
		help_text=mark_safe("Choose all the services that your organisation offers. <a href='https://www.thegreenwebfoundation.org/directory/services-offered/'>More information on our services</a>")
	)
```

You'd probably tidy up the formatting but that should get it working, ready to tidy up in code review.

More below:
https://docs.djangoproject.com/en/4.1/ref/utils/#django.utils.safestring.mark_safe

This isn't the only way, and but it should be enough to unblock you until code review

**Comment by tortila** [comment]
Adding on top of @mrchrisadams's answer: an alternative to `mark_safe` function is to use [a `safe` filter](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#safe) directly in the template, like so:
https://github.com/thegreenwebfoundation/admin-portal/blob/8361834e00fa8805fd04d8898a89847ec248eaf3/apps/accounts/templates/provider_registration/evidence.html#L69
