### ISSUE TITLE
Partner: None

### ISSUE THREAD

**Issue by jonathan-s** [thegreenwebfoundation/admin-portal#42]
This shows up for a user that registers a new hostingprovider. Ideally it should display something different here. Like not a partner. Or perhaps even a link to: How to become a partner or something similar.

**Comment by jonathan-s** [comment]
This is linked to what happens here -> https://github.com/thegreenwebfoundation/greenwebfoundation-admin/blob/5052bbff28171d6321b8108e7720abf148fc6edb/apps/accounts/models/choices.py#L22

**Comment by hanopcan** [comment]
This issue is a legacy one that's no longer relevant as we don't have a partnership scheme anymore or capture that info in our dataset. I'm closing this issue.
