### ISSUE TITLE
[BUG] Fix the hyperscaler importers

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#425]
The daily importers for AWS, Microsoft and Equinix need some love, as they're not updating the hosting info properly in daily updates anymore.

I think this is related to the refactoring work done a while back, so we'd need to revisit all the importers to check they're importing as expected.

**Comment by hanopcan** [comment]
This is being worked on as part of release 1.5. Trello details here: https://trello.com/c/623CQb14/173-look-at-how-to-fix-automated-importer

@mrchrisadams we might be able to close this off soon?

**Comment by mrchrisadams** [comment]
These are set set up via ansible to run, with #554
