### ISSUE TITLE
The current full list of urls for exports has many invalid hostnames

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#45]
After working on updating the greenweb data export, I've realised that we have a lot of invalid hostnames.

This is bad for a few reasons, not least for our own releases of data, like richer versions of the the url2green dataset.

Ideally we'd have a decent white list of urls that are meaningful.

I think we could do this by doing something like:

- make a list of ALL the urls 
- run this list against a checker to only return valid hostnames
- maintain this list
- add the most recent info for each url in this subset
- add it to the export management task that Jonathan created before

**Comment by jonathan-s** [comment]
can you give an example of an invalid hostname?

**Comment by mrchrisadams** [comment]
If you export a query of all the urls, a bit like this (edited for brevity):

```sql
SELECT DISTINCT url from greencheck 
```

Then if you run a check of the urls, you'll find examples of spaces, commas, and characters and so on in the urls:

```bash
# take the first 400 hundred from a list of urls then from that, take the last 10, 
# to simulate an offset
head -n 400 all_domains_outfile.txt | tail -n 10

***.pichunter.com
***.ucoz.ru
***.xgameforce.altervista.org
***site_variable_link_domain***.az-pneus.fr
**YOURACCOUNT**.visualstudio.com
*.academic.ru
*.acturisstaging.flywheelsites.com
*.alarmportal.io
*.amarotic.com
*.amstellanden.nl
```

You can get a whitelist of only green urls.

From this we can do a lookup somewhat your earlier stored procedure, to fetch the last result in greencheck for the url.
