### ISSUE TITLE
[ENHANCEMENT]  Update the service listings to represent our directory

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#461]
For a while we have offered the chance for providers to list the kinds of services they offer beyond shared hosting, as part of the whole "green your stack" concept we've been talking about for a while.

https://www.thegreenwebfoundation.org/directory/services-offered/

We need to update the list of services accordingly in preparation for releasing a new directory designed to allow for filtering by the kind of service you are looking for, and where in the world you are looking for it.

**Comment by hanopcan** [comment]
We launched the beta version of our new Directory last week. Syncing up the services lists got addressed in the middle of last year so I am closing this issue.
