### ISSUE TITLE
[BUG] Changing location for IP-to-CO2Intensity on reload

### ISSUE THREAD

**Issue by ArneTR** [thegreenwebfoundation/admin-portal#545]
**Describe the bug**
When using the Endpoint [https://api.thegreenwebfoundation.org/api/v3/ip-to-co2intensity/217.254.80.109](https://api.thegreenwebfoundation.org/api/v3/ip-to-co2intensity/217.254.80.109) I get varying results.

Just by hitting the reload button in the browser I get two different results:
- A: `{"country_name":"World","country_code_iso_2":"xx","country_code_iso_3":"xxx","carbon_intensity_type":"avg","carbon_intensity":442.23,"generation_from_fossil":61.56,"year":2021,"checked_ip":"217.254.80.109"}`
- B: `{"country_name":"Germany","country_code_iso_2":"DE","country_code_iso_3":"DEU","carbon_intensity_type":"avg","carbon_intensity":367.518,"generation_from_fossil":44.28,"year":2021,"checked_ip":"217.254.80.109"}`

**To Reproduce**
1. Go to [https://api.thegreenwebfoundation.org/api/v3/ip-to-co2intensity/217.254.80.109](https://api.thegreenwebfoundation.org/api/v3/ip-to-co2intensity/217.254.80.109)

**Expected behavior**
I expect only one location to be returned.

**Actual behavior**
I sometimes get *Germany* and sometimes get *World* as location

**Visual proof**
Not applicable

**Environment**
 - Browser [Version 1.61.114 Chromium: 120.0.6099.199 (Official Build) (arm64)](https://brave.com/latest/)
 - Also happens in `curl` and any other browser for me

**Additional context**
No additional context

**Comment by mrchrisadams** [comment]
Thanks @ArneTR  - that _is_ weird. I'm able to reproduce the issue by hitting the API too.

I'll need to look into it more detail this week to see why this is happening, because it's not obvious to me why this would be happening (could it be DNS? I'd normally think so, but we're already working with an IP)

Thanks again for the detailed bug report.

**Comment by mrchrisadams** [comment]
I think I've figured this out.

We have multiple app servers, and each server does the geo-lookup using a special IP to geo lookup file of the kind linked below:

https://db-ip.com/db/format/ip-to-city-lite/mmdb.html

If these are not all in sync, then a request being served by one app server can be different to another one, and we have a round-robin set up.

The ideal scenario would be that we store this info in the same central database, but that involves a few more steps.

What might make more sense might be make sure there's a recurring cron job that updates all servers at roughly the same time.

**Comment by mrchrisadams** [comment]
OK, this is working as intended now - we have all the servers being updated with the same Geo to IP file, and hitting this should give the same consistent result.

https://api.thegreenwebfoundation.org/api/v3/ip-to-co2intensity/217.254.80.109


Thanks letting me know @ArneTR !
